library/urls.py
from django.urls import path, register_converter

from . import converters, views

register_converter(converters.TableConverter, "table")


app_name = 'library'
urlpatterns = [
    path("", views.index, name="index"),
    path("<table:table>/<int:pk>", views.detail, name="detail"),
    path("search", views.list, name="search"),
    path("search/<table:table>", views.list, name="search_json"),
    path("<table:table>", views.list, name="list"),
    path("<table:table>s", views.list, name="list"),
    path("<table:table>/create", views.create, name="create"),
    path("album/bulk_modify", views.bulk_modify, name="bulk_modify"),
    path("<table:related>/<int:related_pk>/create/<table:table>", views.create, name="create"),
    path("<table:table>/<int:pk>/delete", views.delete, name="delete"),
    path("<table:table>/<int:pk>/update", views.create, name="update"),

    path("accounts/profile", views.profile, name="profile"),
    path("accounts/profile/<int:pk>", views.profile, name="profile"),

    path("actions", views.ActionListView.as_view(), name="actions"),
    path("leaderboard", views.leaderboard, name="leaderboard"),

    path("api/music", views.music_api, name="music_api"),
]

wrct_reviews/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.admin import AdminSite
from django.views.generic import TemplateView

class LibraryAdminSite(AdminSite):
    def has_permission(self, request):
        return request.user.is_authenticated and request.user.auth_level == 'Admin'

admin_site = LibraryAdminSite(name='library_admin')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include("library.urls")),
    path('underwriting', TemplateView.as_view(template_name='underwriting.html'), name='underwriting'),
]

reviews/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User

class Artist(models.Model):
    artist = models.CharField(max_length=255, default='')
    short_name = models.CharField(max_length=6, null=True, blank=True)
    comment = models.TextField(null = True, blank = True)

    def __str__(self):
        return self.artist

    class Meta:
        unique_together = ('artist', 'short_name',)



class Label(models.Model):
    label = models.CharField(max_length=255, default='')
    contact_person = models.CharField(max_length=80, null=True, blank=True)
    email = models.CharField(max_length=80, null=True, blank=True)
    address = models.CharField(max_length=80, null=True, blank=True)
    city = models.CharField(max_length=80, null=True, blank=True)
    state = models.CharField(max_length=2, null=True, blank=True)
    phone = models.CharField(max_length=80, null=True, blank=True)
    comment = models.TextField(null = True, blank = True)

    def __str__(self):
        return self.label

class Genre(models.Model):
    genre = models.CharField(max_length=80, default='')

    def __str__(self):
        return self.genre

class Album(models.Model):
    album = models.CharField(max_length=255, default='')
    artist = models.ForeignKey(Artist, on_delete=models.SET_NULL, null=True, blank=True)
    label = models.ForeignKey(Label, on_delete=models.SET_NULL, null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True)
    year = models.PositiveSmallIntegerField(null=True, blank=True)
    date_added = models.DateTimeField(default=timezone.now, null=True)

    STATUS_CHOICES = [
        ("Bin", "Bin"),
        ("N&WC", "N&WC (??)"),
        ("NIB", "Not in bin"),
        ("TBR", "To be reviewed"),
        ("OOB", "Out of bin"),
    ]

    status = models.CharField(max_length=4, null=True, blank=True, choices=STATUS_CHOICES)

    def __str__(self):
        return self.album

class Review(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    date_added = models.DateTimeField(default=timezone.now)
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True)
    review = models.TextField(default='')

    def __str__(self):
        return f"review by {self.user}"

library/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseServerError
from django.urls import reverse
from django.views import generic
from .models import (
    User, Review, Album,
    LibraryEntry,
    ADDITION, CHANGE, DELETION,
    DETAIL_FIELDS, SEARCH_FIELDS, LIST_FIELDS, SORTABLE_FIELDS,
)

from datetime import datetime, timedelta
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from django.contrib import messages
from django.apps import apps
from django.db.models import Q, Count
from .forms import (
    SearchForm,# AlbumSearchForm,
    AlbumForm,
    ArtistForm,
    LabelForm,
    GenreForm,
    SubgenreForm,
    ReviewForm,
    UserForm,
    BulkModifyAlbumForm,
    BulkModifyListForm,
)
from urllib.parse import urlencode

import requests
import json
import os

PAGINATION_COUNT = 25
ORDERING_SUFFIX = "_o"
def add_table(request, table_dict, queryset, param, name=None, count=PAGINATION_COUNT, fields=None):
    """
    request: the WSGI request object
    table_dict: dict to add the generated, paginated/ordered queryset to
    queryset: the queryset/collection of objects to paginate/order
    param: the page parameter for the table (page, albums, etc)
    name: optional, the name to call in the template to access this table

    returns: a dictionary with key "name", and values
    * objects -> the table paginator
    * field_orders -> a dictionary  of the field and its sort direction (up arrow/down arrow)
    * param -> the page parameter for the table
    * sortable -> the list of sortable fields
    * fields -> the list of fields that should be displayed in the table
    * count -> the total number of objects in the paginator
    """
    name = name if name else param
    table = queryset.model.__name__

    ordering = request.GET.get(param + ORDERING_SUFFIX)
    field_orders = {}
    if ordering:
        try:
            order_fields = []
            for o in ordering.split("."):
                reverse = o[0] if o.startswith('-') else ''
                fname = o[1:] if o.startswith('-') else o
                if fname in ["album", "artist", "genre", "label", "subgenre"] and fname != table.lower():
                    order_fields.append(f'{reverse}{fname}__{fname}')
                else:
                    order_fields.append(o)

                field_orders[fname] = "▼" if reverse else "▲"
            queryset = queryset.order_by(*order_fields)
        except Exception as e:
            print(e)
            messages.error(request, "invalid ordering parameter")

    objects_paginator = Paginator(queryset, count)
    objects_page_number = request.GET.get(param)
    objects_paged = objects_paginator.get_page(objects_page_number)

    table_dict[name] = {
        "objects": objects_paged,
        "field_orders": field_orders,
        "param": param,
        "sortable": SORTABLE_FIELDS[table],
        "fields": fields if fields else LIST_FIELDS[table],
        'count': queryset.count(),
    }

def index(request):
    review_period = datetime.now() - timedelta(days=30*3)
    reviews = Review.objects.filter(date_added__gt = review_period, date_added__lt=timezone.now())

    album_period = datetime.now() - timedelta(days=30*1)
    albums = Album.objects.filter(date_added__gt = album_period, date_added__lt=timezone.now())

    tables = {}
    add_table(request, tables, reviews, 'reviews', count=10)
    add_table(request, tables, albums, 'albums', count=10)

    searchForm = SearchForm()

    context = {
        "indexView": True,
        "tables": tables,
        "searchForm": searchForm,
    }
    return render(request, "library/index.html", context)

def detail(request, table, pk):
    ModelClass = apps.get_model(app_label='library', model_name=table)
    obj = get_object_or_404(ModelClass, pk=pk)


    tables = {}
    if table == 'Artist' or table == 'Label':
        add_table(request, tables, obj.album_set.all(), 'album')
    elif table == "Album" or table == 'User':
        add_table(request, tables, obj.review_set.all(), 'review')
    elif table == "Genre":
        add_table(request, tables, obj.subgenre_set.all(), 'subgenre')

    context = {
        'table': table,
        'object': obj,
        'fields': DETAIL_FIELDS[table],
        'fieldsDict': DETAIL_FIELDS,

        'tables': tables,
    }
    return render(request, 'library/detail.html', context)

@login_required
def profile(request, pk=None):
    if pk is None:
        pk = request.user.id
    return detail(request, 'User', pk)

def list(request, table = None):
    """
    Produces a list of objects either from a search form, or from a url
    If the request is a post, it means the user submitted a search form
        in that case, parse form info and redirect to the correct url
    Otherwise, request is just a GET
    Given the table, produce paginated results with the specific filter
    """
    # The user is searching
    query = None
    pos = None
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            table = form.cleaned_data.get('table')
            if not table:
                table = 'album'
            query_params = {
                key: form.cleaned_data.get(key) for key in form.fields.keys() if (
                    key != 'table' and form.cleaned_data.get(key)
                )
            }
            if not query_params.get('query'):
                query_params.pop('pos', None)
            #pos = form.cleaned_data.get('pos')
            #query = form.cleaned_data.get('query')
            query_params = urlencode(query_params)
            url = reverse('library:list', kwargs = {'table': table})
            if query_params:
                url += '?' + query_params
            return HttpResponseRedirect(url)
        else:
            messages.error(request, "invalid search form")
            return HttpResponseRedirect(reverse('library:index'))
    elif not table:
        messages.error(request, "invalid url or method")
        return HttpResponseRedirect(reverse('library:index'))

    # we are on the list page formally now
    form = SearchForm(request.GET)
    if not form.is_valid():
        messages.error(request, 'invalid search search form')
        return HttpResponseRedirect(reverse('library:index'))

    # filter objects using the search form
    objects = form.search(table)
    isAlbumSearch = form.isAlbumSearch
    fields = [f for f in LIST_FIELDS[table]]
    if table.lower() == 'album':
        if not (query or isAlbumSearch):
            objects = objects.filter(date_removed__isnull=True)
        # ^unless you're searching for an album, do not show objects that have been
        # removed from the bin
        else:
            fields.insert(fields.index('date_added') + 1, 'date_removed')
        # add in date_removed to the list otherwise


    request.session['search_form_data'] = form.data

    tables = {}
    add_table(request,
              table_dict = tables,
              queryset = objects,
              param = 'page',
              name = "list",
              fields = fields)

    """
    need to decide if we're on an AJAX view here and then return json if so
    """
    isJsonView = "json" in request.resolver_match.view_name

    # redirect to detail page if there's only one match
    if objects.count() == 1 and not isJsonView:
        return HttpResponseRedirect(reverse("library:detail", kwargs={'table': table.lower(), 'pk': objects.first().pk}))

    if isJsonView:
        data = [obj.json for obj in tables['list']['objects']]
        return JsonResponse(data=data, safe=False)

    context = {
        "table": table,
        "form": form,
        "listView": True,
        'isAlbumSearch': isAlbumSearch,

        "tables": tables,
    }
    return render(request, 'library/list.html', context)


CREATE_FORMS = {
    'Album': AlbumForm,
    'Artist': ArtistForm,
    'Genre': GenreForm,
    'Subgenre': SubgenreForm,
    'Label': LabelForm,
    'Review': ReviewForm,
    'User': UserForm,
}
@login_required
def create(request, table, related=None, related_pk=None, pk=None):
    """
    allows you to create an object of the type <table>
    <related> corresponds to an object that gets related to the new object

    so if table is "album", and related is "artist", then that album's artist
    is going to be set to whatever the pk is
    """
    ModelClass = apps.get_model(app_label='library', model_name=table)

    related_obj = None
    if related and related_pk:
        RelatedModelClass = apps.get_model(app_label='library', model_name=related)
        related_obj = get_object_or_404(RelatedModelClass, pk=related_pk)

    obj = None
    if pk:
        obj = get_object_or_404(ModelClass, pk=pk)


    form = CREATE_FORMS[table](data = request.POST or None, related=related, related_obj=related_obj, instance=obj, user=request.user)
    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            if getattr(obj, 'user', None) is None:
                obj.user = request.user
            if table.lower() in ['album', 'review'] and not obj.date_added:
                obj.date_added = timezone.now().date()
            obj.save()
            form.save_m2m()
            verb = 'created' if not pk else 'updated'
            messages.success(request, f"{obj.table} {verb} successfully")

            if table == 'Subgenre' and related == 'Album':
                related_obj.subgenre.add(obj)
            return HttpResponseRedirect(obj.get_absolute_url())

    context = {
        "table": table,
        "object": obj,
        "form": form,
        "related": related_obj,
    }
    return render(request, 'library/create.html', context)

library/templates/library/actions.html
{% extends "base.html" %}
{% load library_filters %}
{% block title %}wrct database : bin actions{% endblock %}

{% block content %}
<main>
  <h1 class='large'>Bin Action Log</h1>
  <a href='{% url "library:index" %}'>&#8592; back to home</a>

  <section class="mt1-5">
  {% include "library/includes/pagination.html" with page=page_obj param="page" %}
  <ul class="action-list">
  {% for action in object_list %}
    <li>
      <code><em>{{action.action_time|date:"M d, Y, h:i a" }}: </em></code>
      {% if action.user %}<a href="{% url 'library:detail' 'user' action.user.id %}">{{ action.user }}</a>{% else %}a deleted user{% endif %}
      {% if action.table == "Review" and action.action == ADDITION %}<code>reviewed</code> the album
      {% else %}<code> {{ action.get_action_display }}</code> the {{ action.table|lower }}{% endif %}
      {% if action.object %}<a href="{% url 'library:detail' action.table|lower action.object_id %}">{{ action.object_str }}</a>
      {% else %}{{ action.object_str }}{% endif %}
    </li>
  {% empty %}
      <li>No one has used the new db yet (or it's just broken, who knows).</li>
  {% endfor %}
  </ul>
  {% include "library/includes/pagination.html" with page=page_obj param="page" %}
  </section>
</main>

{% endblock %}

library/templates/library/bulk_modify.html
{% extends "base.html" %}
{% load static %}
{% load library_filters %}
{% block title %}wrct database : bulk modify{% endblock %}

{% block content %}
<main>
  <h1 class='large'>bulk modify <i>{{ count }}</i> {{ table }}s</h1>
  <a href='{% url "library:list" table|lower %}'>&#8592; back to {{ table }}s</a>
  <p>In the form below, if you modify <i>any</i> of the fields, you will change the value for <i>all</i> currently selected albums. If you leave a field blank, then no changes will be made.</p>
  <h2>Selected albums:</h2>
  <ul class='repeat-cols'>
    {% for album in albums|slice:":50"%}
    <li>{{ album }}</li>
    {% endfor %}
    {% if albums.count > 50 %}
    <li><i>...and more</i></li>
    {% endif %}
  </ul>

  <form class='form mt1-5' method="post" id='modifyForm'>
    {% csrf_token %}
    <div class="grid">
      {{ form }}
    </div>
    <input type="hidden" name="bulk-modify" value="bulk-modify">
    <button type="submit" class="outline mt1-5" name='bulk-modify'>modify all {{ count }} selected {{ table }}s</button>
  </form>
  <h2>Delete</h2>
  <form class='form' method='post' id='deleteForm'>
    {% csrf_token %}
    <input type="hidden" name="delete" value="delete">
    <button type="submit" class="outline delete" name='delete'>delete all {{ count }} selected {{ table }}s</button>
  </form>
</main>

<script>
const deleteForm = document.querySelector('#deleteForm');
const modifyForm = document.querySelector('#modifyForm');
deleteForm.addEventListener('submit', function (event) {
  event.preventDefault();
  const confirmed = confirm('Are you sure you want to continue deleting?');
  if (confirmed) {
      deleteForm.submit();
  }
});

{% if count > 25 %}
modifyForm.addEventListener('submit', function (event) {
  event.preventDefault();
  const confirmed = confirm('Are you sure you want to continue with modifying {{ count }} albums?');
  if (confirmed) {
      modifyForm.submit();
  }
});
{% endif %}
</script>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/create.js' %}"></script>
{% endblock %}

library/templates/library/create.html
{% extends "base.html" %}
{% load static %}
{% load library_filters %}
{% block title %}wrct database : {% if object %}update {{ table }}: {{ object }}{% else %}add a new {{ table }}{% endif %}{% endblock %}

{% block content %}
<main>
  {# if there's no object then show create links for other tables #}
  {% if not object %}{% with tables="album artist genre label review user"|parse_array %}
  <div class="list-links">
    {% for ftable in tables %}<span><a href="{% url 'library:create' ftable %}"{% if ftable == table|lower %} class="active"{% endif %}>{{ ftable|capfirst }}</a> </span> {% endfor %}
  </div>
  {% endwith %}{% endif %}
  <h1 class='large'>{% if object %}update {{ table }}: {{ object }}{% else %}add a new {{ table }}{% endif %}</h1>
  {% if object %}<a href='{% url "library:detail" object.table object.id %}'>&#8592; back to {{ object.table }} {{ object }}</a>
  {% elif related %}<a href='{% url "library:detail" related.table related.id %}'>&#8592; back to {{ related.table }} {{ related }}</a>
  {% else %}<a href='{% url "library:list" table|lower %}'>&#8592; back to {{ table }}s</a>{% endif %}

  <form class='form mt1-5' method="post">
    {% csrf_token %}
    <div class="grid">
      {{ form }}
    </div>
    <button type="submit" class="outline mt1-5">submit</button>
  </form>
</main>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/create.js' %}"></script>
{% endblock %}

library/templates/library/delete.html
{% extends "base.html" %}
{% load library_filters %}
{% block title %}wrct database : delete {{ table }}{% endblock %}

{% block content %}
<main>
  <h1 class='large'>delete {{ table }}: {{ object }}</h1>
  <a href='{% url "library:detail" object.table object.id %}'>&#8592; back to {{ table|lower }} {{ object }}</a>

  <form class='form mt1-5' method="post">
    {% csrf_token %}
    {% if canDelete %}
    <p>Deleting this object <em>cannot</em> be undone, except by restoring a database backup.</p>
    {% if request.user.auth_level|lower != "admin" %}<p>Incorrectly deleting this {{ table }} will likely cause your ISM a lot of work. Are you sure you want to proceed?</p>
    {% else %}<p>You're the ISM, it'll be your mess.</p>{% endif %}
    {% else %}
    <p>Becuase this {{ table }} has associated objects related to it (reviews, albums, etc), it can only be deleted by an admin. Contact your ISM!</p>
    {% endif %}
    <button type="submit" class="outline" {% if not canDelete %}disabled="true"{% endif %}>that's right, nuke 'em</button>
  </form>
</main>
{% endblock %}

library/templates/library/detail.html
{% extends "base.html" %}
{% load static %}
{% load library_filters %}
{% block title %}wrct database : {{ object }}{% endblock %}

{% block content %}
<main class='detail'>
  <h1 class='large'>{{ table }}: {{ object }}</h1>
  <a href='{% url "library:list" object.table %}'>&#8592; back to {{ table }}s</a>
  <div class="grid mt1-5">
    {% for field in fields %}
    <p class='subtitle'><b>{{ object|verbose_name:field }}: </b><span>{% formatted_attribute object field %}</span></p>
    {% endfor %}
  </div>

  <aside class='side-panel'>
    <div class='edit-links'>
      <h2>Editing links</h2>
      <ul>
        <li><a href="{% url 'library:update' object.table object.pk %}">Edit this {{ table }}</a></li>
        <li><a href="{% url 'library:delete' object.table object.pk %}">Delete this {{ table }}</a></li>
        {% if table == "Album" %}
        <li><a href="{% url 'library:create' object.table object.pk 'review' %}">Review this {{ table }}</a></li>
        <li><a href="{% url 'library:create' object.table object.pk 'subgenre' %}">Add a subgenre classification for this {{ table }}</a></li>
        {% endif %}
      </ul>
    </div>
    {% if table == "Album" or table == "Artist" %}<div id="api-info" style="display: contents;"></div>{% endif %}
  </aside>

  {% if table == "Album" or table == "User" and tables.review.objects %}
  <section>
    <h1>Reviews</h1>
    {% if not tables.review.objects %}
    <p>There are no reviews for this album yet. Be the first to review it!</p>
    {% endif %}
    {% if table == "Album" %}
    <a href="{% url 'library:create' object.table object.pk 'review' %}">
      <button class="outline mb1">
        Review this album <b class='icon'>+</b>
      </button>
    </a>
    {% endif %}
    {% if object.review_set.all %}
    {% if table == "Album" %}{% include "library/includes/table.html" with table_obj=tables.review fields="user review" %}
    {% else %}{% include "library/includes/table.html" with table_obj=tables.review fields="date_added album review" truncateRows=True %}
    {% endif %}
    {% endif %}
  </section>
  {% elif table == "Label" or table == "Artist" %}
  <section>
    <h1>Related Albums</h1>
    <a href="{% url 'library:create' object.table object.pk 'album' %}">
      <button class="outline mb1">
        Add an album here <b class='icon'>+</b>
      </button>
    </a>
    {% if tables.album.objects %}
    {% include "library/includes/table.html" with table_obj=tables.album fields="album year artist" %}
    {% else %}
    <p>This {{ table|lower }} doesn't have any associated albums.</p>
    {% endif %}
  </section>
  {% elif table == "Genre" %}
  <section>
    <h1>Subgenres</h1>
    <a href="{% url 'library:create' object.table object.pk 'subgenre' %}">
      <button class="outline mb1">
        Add a subgenre here <b class='icon'>+</b>
      </button>
    </a>
    {% if tables.subgenre.objects %}
    {% include "library/includes/table.html" with table_obj=tables.subgenre fields="subgenre" %}
    {% else %}
    <p>This genre doesn't have any associated subgenres.</p>
    {% endif %}
  </section>
  {% endif %}
</main>
{% endblock %}


{% block scripts %}
{% if table == "Album" or table == "Artist" %}
<script>
  const table = "{{ table }}";
  const album = "{{ object.album }}";
  const artist = "{{ object.artist }}";
</script>
<script type="text/javascript" src="{% static 'js/music_api.js' %}"></script>
{% endif %}
{% endblock %}

library/templates/library/index.html
{% extends "base.html" %}
{% block title %}wrct database{% endblock %}

{% block content %}
<main class='big'>
<h1 class='header-h1'>wrct : a database</h1>
<header class='header'>
  <aside>
    <h2>Quick links</h2>
    <ul>
      <li><a href="https://cmu.box.com/s/z90uuq9clj19xsa43rq6p6wq62v3uffk">Digital Bin</a></li>
      <li><a href="https://cmu.box.com/s/jlow52gircgh9l32noxgqhvkdqjk9stp">Digital TBR</a></li>
      <li><a href="https://cmu.box.com/s/pt618hioiowze759rg74y2lyni11ib81">Digital Library</a></li>
      <li class="mt2"><a href="{% url 'library:create' 'album' %}">Add new album to db</a></li>
      <li><a href="{% url 'library:create' 'review' %}">Add new review to db</a></li>
    </ul>
  </aside>

  <div>
    <h2>Hello, <a href='{% url "library:profile" %}'>{{ user }}</a>!</h2>
    <p class='subtitle'><b>DJ name:</b> {% if user.djname %}{{ user.djname }}{% endif %}</p>
    <p class='subtitle'><b>Reviews this semester:</b> {{ user.reviews_this_semester }}</p>
    <p><a href='#'>log out</a></p>
  </div>
</header>

<section>
  <h1>Recent reviews</h1>
  <div class='button-container'>
    <a href="{% url 'library:create' 'review' %}">
      <button class="outline">
        New Review <b class='icon'>+</b>
      </button>
    </a>
    <a href="{% url 'library:list' 'review' %}">
      <button class="outline">
        View all reviews
      </button>
    </a>
  </div>
  {% if tables.reviews.objects %}
  {% include "library/includes/pagination.html" with page=tables.reviews.objects param=tables.reviews.param %}
  {% include "library/includes/table.html" with table_obj=tables.reviews truncateRows=True class="mt1-5" %}
  {% endif %}
</section>

<section>
  <h1>Recent albums</h1>
  <div class='button-container'>
    <a href="{% url 'library:create' 'album' %}">
      <button class="outline">
        New Album <b class='icon'>+</b>
      </button>
    </a>
    <a href="{% url 'library:list' 'album' %}">
      <button class="outline">
        View all albums
      </button>
    </a>
  </div>
  {% if tables.albums.objects %}
  {% include "library/includes/pagination.html" with page=tables.albums.objects param=tables.albums.param %}
  {% include "library/includes/table.html" with table_obj=tables.albums fields="album artist label genre year date_added status" truncateRows=True class="mt1-5" %}
  {% endif %}

  <h2 class='mt1-5'>Advanced album search</h2>
  {% include "library/includes/album_search.html" with form=searchForm %}
</section>

</main>

{% endblock %}

library/templates/library/leaderboard.html
{% extends "base.html" %}
{% load library_filters %}
{% block title %}wrct database : reviews leaderboard{% endblock %}

{% block content %}
<main>
  <h1 class='large'>Reviews Leaderboard</h1>
  <a href='{% url "library:index" %}'>&#8592; back to home</a>

  <p>Tracking the Reviews of our station members because please, people need to make more of these.</p>

  <p>NOTE: the leaderboard currently only reflects reviews submitted on the websites olddb.wrct.org or db.wrct.org. I'm working on factoring in reviews submitted from physical sources and on our box location! ~ cassidy</p>

  <section class="mt1-5">
    <h2>This Semester</h2>
    {% if this_semester %}
    <ol class='leaderboard'>
    {% with this_semester|slice:":10" as this_semester %}{% for user, count in this_semester %}
      <li data-count="{{ count }}" data-rank="{{ forloop.counter }}"><span class='leaderboard-user'>{{ user }}</span><span class='leaderboard-count'>: {{ count }}</span></li>
      {% empty %}
    {% endfor %}{% endwith %}
    </ol>
    {% else %}
    <p>No one has made any reviews yet this semester</p>
    {% endif %}
  </section>

  <section class="mt1-5">
    <h2>All Time</h2>
    <ol class='leaderboard'>
    {% with users|slice:":10" as all_time %}{% for user in all_time %}
    <li data-count="{{ user.review_count }}" data-rank="{{ forloop.counter }}"><span class='leaderboard-user'>{{ user }}</span><span class='leaderboard-count'> {{ user.review_count }}</span></li>
    {% endfor %}{% endwith %}
    </ol>
  </section>
</main>

{% endblock %}

library/templates/library/list.html
{% extends "base.html" %}
{% load static %}
{% load library_filters %}
{% block title %}wrct database : {{ table }}s{% endblock %}

{% block content %}
<main class='big'>
  <div class="list-links">
    {% for ftable, label in form.table.field.choices %}<span><a href="{% url 'library:list' ftable %}"{% if ftable == table|lower %} class="active"{% endif %}>{{ label }}</a> </span> {% endfor %}
  </div>
  <h1 class='large'>{{ table }}s</h1>
  <a href='{% url "library:index" %}'>&#8592; back to home</a>

  <p><a href="{% url 'library:create' table|lower  %}">
    <button class="outline mb1">
      Create a new {{ table }} <b class='icon'>+</b>
    </button>
  </a></p>

  <form action="{% url 'library:search' %}" method="post" class='search-form'>
    {% csrf_token %}
    Find {{ form.table }} that {{ form.pos }} {{ form.query }}
    <button class='small gray' type="submit">search</button>
  </form>

  {% if table|lower == 'album' %}
  <details class='mt1-5'{% if isAlbumSearch %} open=""{% endif %}>
      <summary>Advanced album search</summary>
    {% include "library/includes/album_search.html" with form=form %}
  </details>
  {% if user.canBulkModify %}
  <div>
  <input type="checkbox" id="select-all" name="select-all" />
  <button class='small gray mt1-5'><label for="select-all">select all</label></button>
  </div>
  {% endif %}
  {% endif %}

  {% if tables.list.objects %}
  {% include "library/includes/table.html" with table_obj=tables.list truncateRows=True class="mt1-5" %}
  {% else %}
  <p><em>no results :(</em></p>
  {% endif %}
</main>
{% endblock %}

{% block scripts %}
{% if user.canBulkModify %}
<script>
  const totalCount = {{ tables.list.count }};
  const token = '{% csrf_token %}';
</script>
<script type="text/javascript" src="{% static 'js/bulk_modify.js' %}"></script>
{% endif %}
{% endblock %}